#!/bin/bash
set -xe

PROJECT_DIR="$1"
PROJECT_NAME="$2"

INITIAL_DIR=$(pwd)

echo "Processing $2 from $1"

VIA_LAYOUT="$PROJECT_NAME.json"
KLE_LAYOUT="$PROJECT_NAME-kle.json"
KLE_SVG="$PROJECT_NAME-layout.svg"
KICAD_PRO="$PROJECT_NAME.kicad_pro"
KICAD_SCH="$PROJECT_NAME.kicad_sch"
KICAD_PCB="$PROJECT_NAME.kicad_pcb"
KICAD_DRC="$PROJECT_NAME.drc.json"
KBPLACER_LOG="$PROJECT_NAME.kbplacer.log"
SCH_SVG="$PROJECT_NAME-schematic.svg"
PCB_SVG="$PROJECT_NAME-render.svg"

TMP_SVG_DIR="/tmp/$PROJECT_NAME-svg-tmp"

# in case of running with different home (happens on CI)
mkdir -p $HOME/.config/kicad/9.0/colors
cp $KICAD_CONFIG_PATH/colors/vampire.json $HOME/.config/kicad/9.0/colors \
  || (echo "ignore error" > /dev/null)

cd $PROJECT_DIR

echo "=== kbplacer.kle_serial ===" >> "$KBPLACER_LOG"
python -m kbplacer.kle_serial \
  --in "$VIA_LAYOUT" --inform KLE_VIA --convert-via-encoders --outform KLE_RAW --out "$KLE_LAYOUT" >> "$KBPLACER_LOG" 2>&1

# `layout2image` is not yet part of kbplacer installation,
# must call scripts directly:
echo "=== layout2image.py ===" >> "$KBPLACER_LOG"
python /kicad-kbplacer/tools/layout2image.py --convert-via-encoders --in "$VIA_LAYOUT" --out "$KLE_SVG" -f

echo "=== kbplacer ===" >> "$KBPLACER_LOG"
python -m kbplacer \
  --layout "$KLE_LAYOUT" \
  --create-sch-file \
  --sch-file "$KICAD_SCH" \
  --switch-footprint "$KICAD_3RDPARTY_PATH/footprints/$SWITCH_LIBRARY/Switch_Keyboard_Cherry_MX.pretty:SW_Cherry_MX_PCB_{:.2f}u" \
  --stabilizer-footprint "$KICAD_3RDPARTY_PATH/footprints/$SWITCH_LIBRARY/Mounting_Keyboard_Stabilizer.pretty:Stabilizer_Cherry_MX_{:.2f}u" \
  --diode-footprint "/usr/share/kicad/footprints/Diode_SMD.pretty:D_SOD-123F" \
  --encoder-footprint "/usr/share/kicad/footprints/Rotary_Encoder.pretty:RotaryEncoder_Alps_EC11E-Switch_Vertical_H20mm" \
  --encoder-adjustment "-7.5 -2.5" \
  --create-pcb-file \
  --pcb-file "$KICAD_PCB" \
  --diode "D{} CUSTOM 5.08 4 90 BACK" \
  --route-switches-with-diodes \
  --route-rows-and-columns \
  --log-level "DEBUG" \
  --log-format "%(asctime)s: [%(levelname)s] %(message)s" >> "$KBPLACER_LOG" 2>&1

kicad-cli sch export svg --theme vampire --output "$TMP_SVG_DIR" "$KICAD_SCH"
# schematic svg export creates file in new dir, move it:
mv "$TMP_SVG_DIR"/"$PROJECT_NAME".svg "$SCH_SVG"
rm -rf "$TMP_SVG_DIR"

kicad-cli pcb drc --format json --output "$KICAD_DRC" "$KICAD_PCB"

kicad-cli pcb export svg --exclude-drawing-sheet --page-size-mode 2 --theme vampire \
  -l F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts -o "$PCB_SVG" "$KICAD_PCB"

svg_width=$(xq '.svg."@width"' "$PCB_SVG")
svg_height=$(xq '.svg."@height"' "$PCB_SVG")
background_rect="<rect x=\"0\" y=\"0\" width=$svg_width height=$svg_height fill=\"#282A36\"/>"
sed -i "/<desc>Image generated by PCBNEW <\/desc>/a ${background_rect}" "$PCB_SVG"

optimize_svg () {
    scour --enable-id-stripping --enable-comment-stripping \
      --shorten-ids --create-groups -i "$1" -o "$1.tmp"
    rm "$1"
    mv "$1.tmp" "$1"
}

optimize_svg "$SCH_SVG"
optimize_svg "$PCB_SVG"

zip -r "$PROJECT_NAME.zip" "$KICAD_PRO" "$KICAD_SCH" "$KICAD_PCB"
rm "$KICAD_PRO" "$KICAD_SCH" "$KICAD_PCB"

# remove any remaining temporary files
rm -rf *.lck

# go back to initial directory
cd $INITIAL_DIR
