name: Main Workflow

on:
  push:
  schedule:
    - cron: "0 10 * * *"
      branches:
        - master

jobs:
  check_condition:
    name: Check Condition
    runs-on: ubuntu-latest
    outputs:
      run_generate: ${{ steps.check.outputs.generate }}

    steps:
    - name: Check if required to regenerate
      id: check
      run: |
        if [[ "${{ github.event_name }}" = "schedule" ]]; then
          wget https://raw.githubusercontent.com/adamws/keyboard-pcbs/gh-pages/revision.txt
          previous_revision=$(cat revision.txt)
          current_revision=$(git ls-remote https://github.com/the-via/keyboards.git HEAD | awk '{print $1}')
          echo "Previous used via revision: '$previous_revision'"
          echo "Current via revision: '$current_revision'"

          if [ "$previous_revision" = "$current_revision" ]; then
              echo "Revisions are equal, nothing to regenerate"
              echo "generate=false" >> $GITHUB_OUTPUT
          else
              echo "Revisions are different, run generate"
              echo "generate=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "Event is not a schedule event. Setting generate to true."
          echo "generate=true" >> $GITHUB_OUTPUT
        fi

  generate:
    strategy:
      matrix:
        part: [1, 2, 3, 4, 5, 6, 7, 8]
    name: Generate PCBs and layout images
    runs-on: ubuntu-latest
    needs: check_condition
    if: needs.check_condition.outputs.run_generate == 'true'
    container: admwscki/kicad-kbplacer-primary:7.0.8-lunar

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
    - name: Download KiCad colorscheme
      run: |
        mkdir -p /root/.config/kicad/7.0/colors
        cd /root/.config/kicad/7.0/colors
        wget https://raw.githubusercontent.com/2231puppy/kicad-vampire/master/colors/vampire.json
    - name: Run
      run: |
        python3 via_layouts_to_boards.py generate -n ${{ matrix.part }} -parts 8
    - uses: actions/upload-artifact@v4
      with:
        name: gh-pages-${{ matrix.part }}
        path: gh-pages/*
        retention-days: 1
        if-no-files-found: error

  collect-and-deploy:
    name: Collect and deploy results
    runs-on: ubuntu-latest
    needs: generate
    container: admwscki/kicad-kbplacer-primary:7.0.8-lunar

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python3 -m pip install -r requirements.txt
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: gh-pages
        pattern: gh-pages-*
        merge-multiple: true
    - name: Run
      run: |
        python3 via_layouts_to_boards.py collect -gh
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./gh-pages
        enable_jekyll: false
        force_orphan: true

